spring:
  application:
    name: userorder
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:userorder}?useSSL=false
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:123}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:8000}
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka
